# Site settings
title: "Marek Kurdej"
email: firstname.surname@gmail.com
description: "Blog of Marek Kurdej"
baseurl: ""
url: https://mkurdej.github.io
enforse_ssl: mkurdej.github.io
title_description: "Blog of Marek Kurdej."
title_image: "https://secure.gravatar.com/avatar/8cac760da31f8b2e6edcdcaac27fd41c"
post_limit: 5

# Social usernames/URLs
twitter_username: Kurdej
github_username:  mkurdej
linkedin_link: https://www.linkedin.com/in/mkurdej/
stackoverflow_link: https://stackoverflow.com/users/1032917/marek-kurdej
disqus_account: mkurdej
google_analytics:

# Footer
footer_right: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noir</a> theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_center: "&copy; 2017 <a href=\"https://twitter.com/mkurdej\">Marek Kurdej</a>"
footer_left: "&lt;/&gt; on <a href=\"https://github.com/mkurdej/mkurdej.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM

permalink: pretty
exclude: [vendor]

#RSS
name: "Marek Kurdej's Blog"

redirects: yes
permalink: /:title/

gems:
  - jekyll-redirect-from

